global:
  resolve_timeout: 5m

# 报警模板文件
templates:
  - 'default.tmpl'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 600s
  repeat_interval: 1h
  receiver: 'wechat'
receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://127.0.0.1:5001/'
- name: 'DingDing'
  webhook_configs:
  - url: 'http://dingtalk:8086/dingtalk/webhook1/send' 
    send_resolved: true
- name: 'wechat'
  wechat_configs:
  - send_resolved: true
    corp_id: 'wwd123456789'
    to_party: '3'
    to_user: 'username|tom|hanmeimei'
    agent_id: '1000004'
    api_secret: 'ncvhKhQ38LyF123456'
    message: '{{ template "marathon.message" . }}'
#inhibit_rules:
#  - source_match:
#      severity: 'critical'
#    target_match:
#      severity: 'warning'
#    equal: ['alertname', 'dev', 'instance']
