version: '3.2'
services:
  prometheus:
    image: sxlsteven/monitor:prometheus1.0.0
    container_name: prometheus
    user: root
    #network_mode: "host"
    restart: always
    ports:
      - 9090:9090
    links:
      - alertmanager
      - consul
    volumes:
      - /data/monitor-data/prometheus:/prometheus:rw
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./alerting_rule:/etc/prometheus/alerting_rule:ro
      - ./probes:/etc/prometheus/probes

  alertmanager:
    image: sxlsteven/monitor:alertmanager1.0.0
    container_name: alertmanager
    user: root
    #network_mode: "host"
    restart: always
    ports:
      - 9093:9093
      - 9094:9094
    links:
      - dingtalk
    volumes:
      - /data/monitor-data/alertmanager:/alertmanager:rw
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - ./default.tmpl:/etc/alertmanager/default.tmpl:ro

  dingtalk:
    image: sxlsteven/monitor:dingtalk1.0.0
    container_name: dingtalk
    user: root
    #network_mode: "host"
    restart: always
    #ports:
    #  - 8086:8086
    volumes:
      - ./config.yml:/usr/local/dingtalk/config.yml:ro

  grafana:
    image: sxlsteven/monitor:grafana1.0.1
    container_name: grafana
    user: root
    #network_mode: "host"
    restart: always
    links:
      - dingtalk
      - prometheus
      - alertmanager
      - consul
    ports:
      - 3000:3000
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "10"
    volumes:
      - /data/monitor-data/grafana:/var/lib/grafana:rw
      - ./grafana.ini:/etc/grafana/grafana.ini:ro
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone

  consul:
    image: sxlsteven/monitor:consul1.0.0
    container_name: consul
    user: root
    restart: always
    ports:
      - 8500:8500
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    volumes:
      - ./consul:/consul 
