apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

namespace: monitoring

commonLabels:
  app: alertmanager-webhook-dingtalk

replicas:
  - name: alertmanager-webhook-dingtalk
    count: 1

images:
  - name: timonwong/prometheus-webhook-dingtalk
    newTag: v1.4.0

configMapGenerator:
  - name: alertmanager-webhook-dingtalk
    files:
      - config/config.yaml
      - config/template.tmpl
