version: '3.2'
services:
  prometheus:
    image: sxlsteven/monitor:prometheus1.0.0
    container_name: prometheus
    user: root
    #network_mode: "host"
    restart: always
    ports:
      - 9090:9090
    links:
      - alertmanager
    #command:
    #  - --web.enable-lifecycle
    #  - --config.file=/etc/prometheus/prometheus.yml
    #  - --storage.tsdb.path=/prometheus
    #  - --web.console.libraries=/usr/share/prometheus/console_libraries
    #  - --web.console.templates=/usr/share/prometheus/consoles
    #  - --storage.tsdb.retention=180d
    volumes:
      - /data/prometheus:/prometheus:rw
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./alerting_rule:/etc/prometheus/alerting_rule:ro
      #- ./recording_rule:/etc/prometheus/recording_rule:ro

  alertmanager:
    image: sxlsteven/monitor:alertmanager1.0.0
    container_name: alertmanager
    user: root
    #network_mode: "host"
    restart: always
    ports:
      - 9093:9093
      - 9094:9094
    links:
      - dingtalk
    #command:
    #  - --storage.path=/alertmanager
    #  - --data.retention=120h
    #  - --config.file=/etc/alertmanager/alertmanager.yml
    volumes:
      - /data/alertmanager:/alertmanager:rw
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - ./default.tmpl:/etc/alertmanager/default.tmpl:ro

  dingtalk:
    image: sxlsteven/monitor:dingtalk1.0.0
    container_name: dingtalk
    user: root
    #network_mode: "host"
    restart: always
    ports:
      - 8086:8086
    #command:
    #  - --storage.path=/alertmanager
    #  - --data.retention=120h
    #  - --config.file=/etc/alertmanager/alertmanager.yml
    volumes:
      - ./config.yml:/usr/local/dingtalk/config.yml:ro

  grafana:
    image: sxlsteven/monitor:grafana1.0.0
    container_name: grafana
    user: root
    network_mode: "host"
    restart: always
    #ports:
    #- 3333:3000
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "10"
    #command:
    #  - 
    environment:
      - INFLUXDB_PORT=8086
      - INFLUXDB_NAME=cadvisor
      - INFLUXDB_USER=cadvisor
      - INFLUXDB_PASS=cadvisor
      - INFLUXDB_HOST=192.168.10.78
    volumes:
      - /data/grafana:/var/lib/grafana:rw
      - ./grafana.ini:/etc/grafana/grafana.ini:ro
